version: "3.8"

services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - PORT=3000
    # Monta el proyecto para desarrollo y evita sobreescribir node_modules del contenedor
    volumes:
      - ./:/app
      - /app/node_modules
    stdin_open: true
    tty: true
